spring:
  cloud:
    gateway:
      routes:
        - id: notification-service
          uri: http://localhost:8081/
          predicates:
            - Path=/notification-service/**
        - id: customer-service
          uri: http://localhost:9001/
          predicates:
            - Path=/customer-service/**